---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: update_cache=yes upgrade=yes
      become: yes

  roles:
    - git
    - ruby
    - vim

  tasks:
    - name: Install avahi for multicast DNS/DNS-SD service discovery
      apt: pkg=avahi-daemon
      become: yes
