---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes

  roles:
    - avahi
    - git
    - ruby
    - vim
    - adr-tools
    - plantuml
    - python
    - semgrep

  post_tasks:
    - name: Set python3 as default python
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3
      become: yes
