---
- hosts: all

  pre_tasks:
    - name: Update apt cache and upgrade
      apt: update_cache=yes upgrade=yes
      become: yes

  roles:
    - avahi
    - git
    - ruby
    - vim
    - adr-tools
    - plantuml
