name: Test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.1'

    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.15
        python -m pip install --upgrade pip semgrep

    - name: Run the default task
      run: |
        bin/setup
        bin/test

    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          coverage
          rspec_results.html
          rubocop.html
          semgrep-ci.xml
          semgrep-docker.xml
          semgrep-ruby.xml
          semgrep-security.xml
